services:
  kanban:
    build: .
    ports:
      - "${EXTERNAL_PORT:-8000}:8000"
    volumes:
      # Persist database and backup files
      - kanban_data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - DATA_DIR=/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000}/api/tasks"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  kanban_data:
    driver: local
